# auto-generated by x2py xpiler

import x2py

class HelloReq(x2py.Event):
    tag = x2py.Event.Tag(x2py.Event.tag, 'HelloReq', 1,
        1)

    def __init__(self, length=0):
        super().__init__(HelloReq.tag.num_props + length)
        self._name = ""

    @property
    def name(self):
        return self._name
    @name.setter
    def name(self, value):
        self._name = value

class HelloResp(x2py.Event):
    tag = x2py.Event.Tag(x2py.Event.tag, 'HelloResp', 1,
        2)

    def __init__(self, length=0):
        super().__init__(HelloResp.tag.num_props + length)
        self._message = ""

    @property
    def message(self):
        return self._message
    @message.setter
    def message(self, value):
        self._message = value
